# Generated by Django 5.2.7 on 2025-11-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='detalle',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
